### ISSUE TITLE
Have some troubles on first lunch

### ISSUE THREAD

**Issue by CirlanDumitru** [Pluso/PlusoSDK-iOS#1]
```
dyld: Library not loaded: @rpath/PlusoSDK.framework/PlusoSDK
  Referenced from: /private/var/mobile/Containers/Bundle/Application/FECC7EE5-2B90-49A7-A53F-04F4757D219D/testPULSO.app/testPULSO
  Reason: image not found
(lldb) 
```

Any advice ?

**Comment by sidorov-panda** [comment]
Hello! Did you follow the instructions from this page https://github.com/Pluso/PlusoSDK-iOS/wiki#installation ? PlusoSDK should be added to _Embedded binaries_ of your target.

Please, provide more info

**Comment by CirlanDumitru** [comment]
don't have much information, i had created a test app and follow the installation instruction, and get the error that i mentioned above.

**Comment by sidorov-panda** [comment]
Please, take a look at this demo project https://github.com/sidorov-panda/PlusoSDKTestProject
Can you run it?

**Comment by CirlanDumitru** [comment]
Yep, all work just fine, but just for share purpose 

```
@property (nonatomic, assign) IBInspectable PLSDKActivityType type;
    PLSDKActivityTypeRate = 0,
    PLSDKActivityTypeShare,
```

don't change nothing, TypeRate and TypeShare call share view in both cases

**Comment by sidorov-panda** [comment]
Could you show your ActionBar configuration? Where do you configure it?
In IB you have to set Action Type to "share" or "rate".
In code you have to set
`actionBar.type = PLSDKActivityTypeRate;`

or

`actionBar.type = PLSDKActivityTypeShare;`

Updated for rate. Please, take a look https://github.com/sidorov-panda/PlusoSDKTestProject

**Comment by CirlanDumitru** [comment]
```
PLSDKActionBar *actionBar = [[PLSDKActionBar alloc] initWithFrame:CGRectMake(0, 519, 320, 49)];
actionBar.type = PLSDKActivityTypeRate;
actionBar.feedbackEmail = @"support@youremail.com";
actionBar.shareURLString = @"https://itunes.apple.com/ru/app/luuk-zakazi-manikur-ukladku/id931968289?l=en&mt=8";
actionBar.delegate = self;
```

configuration was from repo usage section

last update work just fine, thx.
