### ISSUE TITLE
multiple errors when posting to AppStore

### ISSUE THREAD

**Issue by amykhajlyshyn** [Pluso/PlusoSDK-iOS#2]
When I add PlusoSDK to embedded frameworks as described in documentation I cannot post ipa to AppStore, it fails with errors:

```
    ERROR ITMS-90087: "Unsupported Architectures. The executable for ***.app/Frameworks/PlusoSDK.framework contains unsupported architectures '[x86_64, i386]'."
    ERROR ITMS-90362: "Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle ***.app/Frameworks/PlusoSDK.framework is invalid. The minimum value is 8.0"
    ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at '***.app/Frameworks/PlusoSDK.framework/PlusoSDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
    ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
```

This issue does not occur when I remove SDK from embedded frameworks. Do you have any suggestions?

Thanks,
Andrew

**Comment by sidorov-panda** [comment]
Have you tried this answer
http://stackoverflow.com/questions/25909870/xcode-6-and-embedded-frameworks-only-supported-in-ios8/28703657#28703657

Could you specify more info?

**Comment by amykhajlyshyn** [comment]
Yes, I already checked multiple answers and still no luck. This particular answers describes the case with dynamically linked framework. From what I see PlusoSDK is statically linked framework and the only reason to add it to embedded frameworks is adding it's assets to the ipa. I think the correct way to move all assets to separate bundle and distribute SDK as framework + bundle.

If you need more info, could you please specify what exactly do you need. Thanks!

**Comment by sidorov-panda** [comment]
Especially for ios 7, PlusoSDK stores all the assets statically right inside the framework as static C arrays, so it is no need to include additional bundle or something. Also it includes compiled assets to be used on ios8+, but I don`t know is it make sense in this case.

Please specify your development target, 
Build Active Architecture Only = ?
Architectures = ?
Valid architectures = ?

**Comment by sidorov-panda** [comment]
Please, take a look at this blog post
http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/
I think this is the answer, because PlusoSDK was compiled as dynamic library. I will test it today.

**Comment by amykhajlyshyn** [comment]
Build Active Architecture Only = No,
Architectures = arm64, armv7
Valid Architectures = arm64, armv7, i386, x86_64.

Actually, I was able to post ipa to app store without embedding framework, just linking it. I tested it and it works fine. Which specific features of SDK need framework embedding so I can check it?

**Comment by amykhajlyshyn** [comment]
Hello!

I found that other frameworks have the same issue when building with min deployment target ios 7:
https://github.com/Carthage/Carthage/issues/351
https://github.com/SnapKit/SnapKit/issues/87

It works fine when installing ipa on ios 7 device but I cannot submit it to appstore when min deployment target is ios 7 :(

**Comment by sidorov-panda** [comment]
It`s strange, I`ll try to find how to deal with this in the right way.
Did you submit your app to App Store with linked framework or you are waiting for solution?

**Comment by amykhajlyshyn** [comment]
I'm waiting for solution. Without embedding framework it does not even start. Thanks!

**Comment by sidorov-panda** [comment]
Just compiled it as a static framework. Will try to find time to test it carefully. Please, take a look

Branch
https://github.com/Pluso/PlusoSDK-iOS/tree/static-framework

Installation:
Copy to your project and link as shown below
![screen shot 2015-07-08 at 15 55 01](https://cloud.githubusercontent.com/assets/2707839/8570550/c43bb672-2589-11e5-932f-d2e4cd77472e.png)

**Comment by amykhajlyshyn** [comment]
Thank you! This build works fine. I'm closing this issue.
